### ISSUE TITLE
Running with interactive agent causes null reference from missing parameter

### ISSUE THREAD

**Issue by Phantomb** [tesslerc/malmo_rl#2]
`Helpers.py` throws an exception [at line 52](https://github.com/tesslerc/malmo_rl/blob/14390e32dd7d1a76aceac9ec1e5144904ab09233/utilities/helpers.py#L52-L55) when used with the `interactive` agent because that agent is missing the `learn_start` parameter:
```
PS C:\Github_Repos\tessler_Malmo> python main.py interactive single_room
INFO: To view results, run 'python -m visdom.server'
INFO: then head over to http://localhost:8097
INFO: Starting Malmo:
INFO: Malmo loaded!
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    viz)
  File "C:\Github_Repos\tessler_Malmo\utilities\helpers.py", line 52, in play_full_episode
    if step > params.learn_start and is_train:
AttributeError: 'Namespace' object has no attribute 'learn_start'
PS C:\Github_Repos\tessler_Malmo>
```

A simple check if that parameter exists might suffice, but I'm not sure if you would maybe rather want to check for / catch that error in some other way.

**Comment by tesslerc** [comment]
Fixed in a6ce0b13965e71e750649df75a30d410ae46c4e3.
This is a dirty fix, but since the interactive agent is only here for manual testing of the environment I think it's better this way, over adding additional logic to the main code.
