### ISSUE TITLE
Running with DQN agent is visually slow and hangs without throwing an exception

### ISSUE THREAD

**Issue by Phantomb** [tesslerc/malmo_rl#3]
After executing the agent with the standard parameters as such: `python main.py dqn single_room --double_dqn --normalize_reward`, the world is built as normal and the agent starts acting in the world.

However, the minecraft client seems visually very slow, laggy or missing frames. The visdom window in the browser however shows more visual frames being captured than that the client shows.

After ~10 seconds of acting, both the minecraft client and the terminal seem to hang indefinitely and are unresponsive. The terminal does not produce any further logged or printed messages, nor does the visdom window produce any frames. After forcibly closing the minecraft client, the terminal continues reporting the following exceptions every few seconds:

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Github_Repos\tessler_Malmo\agents\agent.py", line 116, in _load_mission_from_xml
    self.agent_host.startMission(mission, self.client_pool, mission_record, 0, str(self.experiment_id))
agents.malmo_dependencies.MalmoPython.MissionException: Failed to find an available client for this mission - tried all the clients in the supplied client pool.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Program Files\Anaconda3\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Program Files\Anaconda3\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Github_Repos\tessler_Malmo\utilities\parallel_agents_wrapper.py", line 54, in agent_perform_action
    reward, terminal, state, terminal_due_to_timeout = agent.perform_action(action)
  File "C:\Github_Repos\tessler_Malmo\agents\agent.py", line 142, in perform_action
    self._restart_world()
  File "C:\Github_Repos\tessler_Malmo\agents\single_room.py", line 31, in _restart_world
    self._load_mission_from_xml(mission_xml)
  File "C:\Github_Repos\tessler_Malmo\agents\agent.py", line 121, in _load_mission_from_xml
    logging.critical('_load_mission_from_xml, Error starting mission', e)
Message: '_load_mission_from_xml, Error starting mission'
Arguments: (MissionException('Failed to find an available client for this mission - tried all the clients in the supplied client pool.',),)
```
But I expect that all these exceptions are due to the client no longer running.

I cannot forcibly interrupt the process in the terminal other than closing the window.

For completeness, you can see the full behaviour recorded here: https://youtu.be/tzDqEF1s2wk . Around 1:20, the world finished building and the agent starts interacting. Around 1:30, the windows become unresponsive and start to hang indefinitely.

**Comment by tesslerc** [comment]
Thanks!
Due to this flag "<PrioritiseOffscreenRendering>true</PrioritiseOffscreenRendering>" in the mission XML file, it causes Malmo to render the state sent to us faster and update the actual minecraft window less often.
This provides better performance, and doesn't effect what the agent sees.

Take a look at commit 4326e96334a982a1a2fbeffe120331a57d6272bc which should be stable.
The previous behavior was to allow malmo to detect game over and then request a mission restart. This seems to be buggy. I found that manually teleporting the agent to the start location is not only faster but also less prone to failures.

That said, I still need to refactor the error checking mechanism. The issue when it hangs that you can not stop the agent is since it runs in separate threads.

**Comment by Phantomb** [comment]
Hmm it seems that exact commit (and some commits coming after it) messed with the indentation and newlines of multiple files. For example in the policy/dqn at [create_model](https://github.com/tesslerc/malmo_rl/blob/9fb1e1d36894c32a17435278b7791804f5e62fb9/policies/dqn.py#L47), and a lot of other places.

Most of those I can fix myself, but I'd need the guarantee that no single line of code is missing or is placed in the wrong order. And even then, at some places multiple different results might be correct, without knowing the intended indentation (e.g. in the larger if-statement branches).

Curious how that happened!

**Comment by tesslerc** [comment]
Sorry about that, didn't notice that happened.
Probably since I work simultaneously on two different computers on the same files.
I did a diff check and as far as I can see it should be fixed and without any newly introduced logical issues. Fixed in fee6517700ab2eace084e6680997049ba804dc33.

I'll keep checking and I'll update if I find any new issues. I'll also try adding a better way to cope with Malmo issues.

**Comment by tesslerc** [comment]
Added better error handling in 09c95ba318038bff7d6032bddc8d7a5dfe8aabce.
If Minecraft window hangs, the agent will keep trying to reconnect.
This allows you to re-open Malmo manually and it will reconnect.

I'll try seeing if I can detect if it hangs, close the Minecraft instance and reopen it. Not sure it will be possible though.

**Comment by Phantomb** [comment]
Nice! This issue can be closed I think, since I'm currently doing a run of fee6517 and everything seems to be working, as far as I can tell (at least no indefinite hanging/crashes).

(However, I am wondering when the `avg_reward` and `max_episode_reward` will show some improvement, they seem to only get lower. But that will probably also take some tweaking of the parameters. I am running it on one machine with the default parameters, currently at step 12000.)

**Comment by Phantomb** [comment]
I was letting it run for quite some time, when I noticed the PC had rebooted, erasing all the progress. I presume the reboot was due to some BSOD. It appears to have been stopcode [9F](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x9f--driver-power-state-failure) indicating a driver problem. No idea which may be the culprit, nor why it only randomly occurred after already running for quite a while. I'll try updating any drivers I have tomorrow.

Being able to periodically save the thus-far trained model might prove beneficial.

**Comment by tesslerc** [comment]
Removed the whole multi-threading part. At least on my end, it caused performance issues and caused the program to hang.
It currently causes a slight slowdown, but I'll find a way to get around it (parallel multiple agents without threads).
Also added more robust error checking so if Malmo crashes etc... restart and it will keep running.

Next will be to implement saving model checkpoints (+ optimizer etc...) to allow for continual learning in case of a crash.
